### ISSUE TITLE
Install Script Error

### ISSUE THREAD

**Issue by Ayy-ay-oos** [tpflueger/CSCI4900#26]
Do Maven does not run after install, error is either in the install script or setup.py

**Comment by tpflueger** [comment]
Can you post the stack trace?

**Comment by Ayy-ay-oos** [comment]
Hi Tyler,

Sorry for the late response, by stack trace do you mean the error that I
receive?

**Comment by tpflueger** [comment]
Yeah, whatever it may be that you saw when it had the issue..

**Comment by tpflueger** [comment]
Seems to be similar to other created issue which has been fixed.
